GET http://localhost:8000/api/traininsync/

###

POST http://localhost:8000/api/traininsync/
Content-Type: application/json

{
    "dados_bancarios": {
        "numero_conta": 2151657,
        "agencia": 1153
    },
    "nome": "macaquitok",
    "cpf": "97192864072",
    "data_de_nascimento": "1995-08-14",
    "email": "testerator@gmail.com",
    "numero_de_celular": "83995213641",
    "sexo": "M",
    "nome_social": "caco",
    "etnia": "branca",
    "estado_civil": "solteiro",
    "status": true,
    "cref": "teste_de_cref3",
    "especialidades": "king of banana",
    "experiencia_profissional": "comer cu de curioso",
    "horarios_disponiveis": 17,
    "locais_disponiveis": "ducks"
}

###

GET http://localhost:8000/api/traininsync/2/

###

PUT http://localhost:8000/api/traininsync/1/
Content-Type: application/json

{
    "dados_bancarios": {
        "numero_conta": 2151650,
        "agencia": 1143
    },
    "nome": "macaquito",
    "cpf": "40407780068",
    "data_de_nascimento": "1995-08-14",
    "email": "teste2@gmail.com",
    "numero_de_celular": "83995213641",
    "sexo": "M",
    "nome_social": "caco",
    "etnia": "branca",
    "estado_civil": "solteiro",
    "status": true,
    "cref": "teste_de_cref10",
    "especialidades": "king of banana",
    "experiencia_profissional": "comer cu de curioso",
    "horarios_disponiveis": 15,
    "locais_disponiveis": "patos"
}

###

DELETE http://localhost:8000/api/traininsync/2/
