repos:
  - repo: local
    hooks:
      - id: npm-lint
        name: Run ESLint via npm
        entry: bash -c "cd traininSync-front && npm run lint:fix"
        language: system
        pass_filenames: false

      - id: npm-prettier
        name: Run Prettier via npm
        entry: bash -c "cd traininSync-front && npm run prettier:fix"
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
