# Generated by Django 5.2 on 2025-04-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traininsync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoDeServico", models.CharField(max_length=150, unique=True)),
                ("descricaoDoServico", models.TextField()),
                ("valorDoServico", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("bioimpedancia", models.CharField(max_length=15, unique=True)),
                ("altura", models.FloatField()),
                ("idade", models.IntegerField()),
                ("sexo", models.CharField(max_length=50)),
                ("dataDoExame", models.DateField()),
                ("horaDoExame", models.TimeField()),
                ("aguaCorporalTotal", models.FloatField(blank=True, null=True)),
                ("proteinas", models.FloatField(blank=True, null=True)),
                ("minerais", models.FloatField(blank=True, null=True)),
                ("massaGordura", models.FloatField(blank=True, null=True)),
                ("peso", models.FloatField()),
                ("massaMusculaEsqueletica", models.FloatField(blank=True, null=True)),
                ("imc", models.FloatField(blank=True, null=True)),
                ("pgc", models.FloatField(blank=True, null=True)),
                ("taxaMetabolicaBasal", models.FloatField(blank=True, null=True)),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno",
                        to="traininsync.pessoa",
                    ),
                ),
            ],
        ),
    ]
