# Generated by Django 5.2 on 2025-05-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traininsync", "0004_rename_data_do_exame_aluno_data_do_exame_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="pgc",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="bioimpedancia",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="data_do_exame",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="hora_do_exame",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="especialidades",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="experiencia_profissional",
            field=models.TextField(blank=True, null=True),
        ),
    ]
