# Generated by Django 5.2 on 2025-06-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traininsync", "0005_remove_aluno_pgc_alter_aluno_bioimpedancia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrodeprogresso",
            name="imc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="tipo_de_servico",
            field=models.CharField(max_length=150),
        ),
    ]
