# pylint: skip-file
# Generated by Django 5.2 on 2025-06-28 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "traininsync",
            "0007_remove_agenda_reserva_alter_aluno_bioimpedancia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratodeservico",
            name="horario",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="traininsync.agenda",
            ),
        ),
    ]
