# pylint: skip-file
# Generated by Django 5.2 on 2025-06-28 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traininsync", "0008_alter_contratodeservico_horario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratodeservico",
            name="horario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="traininsync.agenda",
            ),
        ),
    ]
