# pylint: skip-file
# Generated by Django 5.2 on 2025-06-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traininsync", "0010_alter_contratodeservico_servico_desejado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratodeservico",
            name="servico_desejado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="traininsync.servico",
            ),
        ),
    ]
