# pylint: skip-file
# Generated by Django 5.2 on 2025-07-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traininsync", "0011_alter_contratodeservico_servico_desejado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="id",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="pessoa",
        ),
        migrations.AddField(
            model_name="aluno",
            name="pessoa_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="traininsync.pessoa",
            ),
            preserve_default=False,
        ),
    ]
