name: Django CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: bdtraininsync
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: senha-traininsync
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r traininSync-back/requirements.txt
        pip install coverage
    - name: Copying configurations
      run: |
        cp .env.example .env
    - name: Export DATABASE_URL
      run: |
        echo "DATABASE_URL=postgresql://admin:senha-traininsync@localhost:5432/bdtraininsync" >> $GITHUB_ENV
    - name: Run migrations
      run: |
        python traininSync-back/manage.py migrate
    - name: Run Tests
      run: |
        python traininSync-back/manage.py test traininsync.tests
    - name: Run tests with coverage
      run: |
        coverage run traininSync-back/manage.py test traininsync.tests
        coverage xml
    - name: Install SonarScanner CLI
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner.zip -d $HOME
        echo "$HOME/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=traininsynckey \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://labens.dct.ufrn.br/sonarqube \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.python.coverage.reportPaths=coverage.xml
